alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'
alias grep='grep --color=auto'
alias l='ls -CF'
alias la='ls -A'
alias ll='ls -alF'
alias logout='loginctl terminate-user dylan'
alias ls='ls --color=auto'
alias rm='rm -i'
alias set-volume='amixer -D pulse sset Master'
alias sleep-off='sudo systemctl mask sleep.target suspend.target hibernate.target hybrid-sleep.target'
alias sleep-on='sudo systemctl unmask sleep.target suspend.target hibernate.target hybrid-sleep.target'
alias sleep-status='sudo systemctl status sleep.target suspend.target hibernate.target hybrid-sleep.target'
alias source-bash='source ~/.bashrc'
alias ss-off='xset s off && xset s noblank && xset -dpms'
alias poweroff='shutdown -h now'
alias bat='batcat'
alias vim='nvim'
alias vi='nvim'
alias laptop='bspc monitor eDP-1 -d I II III IV V VI VII VIII IX X && autorandr -l NewLaptop'
alias bat='upower -i /org/freedesktop/UPower/devices/battery_BAT0 | grep -E "state|to\ full|percentage"'
