# /home/dylan/dotfiles/

name: dotfiles
root: ~/dotfiles/

# Specifies (by name or index) which window will be selected on project startup. If not set, the first window is used.
startup_window: editor

windows:
  - editor:
      # Synchronize all panes of this window, can be enabled before or after the pane commands run.
      # 'before' represents legacy functionality and will be deprecated in a future release, in favour of 'after'
      # synchronize: after
      panes:
        - nvim
  - bash:
    panes:
      - bash
