#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc wm -0 HDMI-0 USB-C-0 DP-4

bspc monitor DP-4 -d VIII IX X
bspc monitor HDMI-0 -d IV V VI VII
bspc monitor USB-C-0 -d I II III

bspc monitor HDMI-0 -s DP-4 -s USB-C-0 


#Autostart applications
sxhkd &
picom --config $HOME/.config/picom/picom.sample.conf/ &
nitrogen --restore &
dunst &
polybar &
autorandr -c &
ss-off &
