#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc monitor DP-4 -d IV V VI
bspc monitor HDMI-0 -d I II III
bspc monitor USB-C-0 -d VIII IX X

bspc monitor DP-4 -s HDMI-0 -s USB-C-0 


#Autostart applications
sxhkd &
picom --config $HOME/.config/picom/picom.sample.conf/ &
nitrogen --restore &
dunst &
polybar &
